### ISSUE TITLE
Login page always show signed in user for personal accounts once if login with MSALForceLogin behaviour.

### ISSUE THREAD

**Issue by suniljakhar** [Azure-Samples/ms-identity-mobile-apple-swift-objc#14]
Hi,
Login page always show signed in user for personal accounts once if login into account even if  i pass MSALForceLogin as login uiBehavior. But for business accounts is always ask for username password if i login with MSALForceLogin as login uiBehavior. According,  MSALForceLogin option it should show login page without showing any signed in user.

**Comment by e-stylzz** [comment]
Were you able to figure anything out with this?

**Comment by oldalton** [comment]
This is a limitation of MSA on the server side. We have an issue opened in MSAL repository to track it: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/817. Closing this one as duplicate.
