### ISSUE TITLE
Using MSAL to clear tokens on Microsoft

### ISSUE THREAD

**Issue by sgby1234** [Azure-Samples/ms-identity-mobile-apple-swift-objc#41]
Hi, 
Is there a way to invalidate tokens?
I am currently using the library and signing out users by calling 
`applicationContext.remove(account)`
This clears the token from the app, but the token is still valid with Microsoft. I would like to completely sign out the user, such that if I were to send a request to Microsoft using the token I would be told that the token is no longer valid. Currently I am making a request to https://graph.microsoft.com/v1.0/me and am passing in my access token to test if I am still signed in with Microsoft.

I've been researching and some people have been saying to call the Microsoft API, `https://login.windows.net/<tenent-id>/oauth2/logout` - but this API brings up a webpage. Is there a way to do this silently and pass in the tokens as a request body?

Thank you!

**Comment by oldalton** [comment]
There's no way to do it silently without bringing up the webpage, as MSAL doesn't have control over ASWebAuthenticationSession. This is an explicit design decision by Apple to ensure security of cookies.
