### ISSUE TITLE
applicationContext.allAccounts() is always empty

### ISSUE THREAD

**Issue by hassanelshairr** [Azure-Samples/ms-identity-mobile-apple-swift-objc#59]
I'm trying to refresh existing token by calling `acquireTokenSilently` as in the demo. However, `applicationContext.allAccounts()` is always empty.

**Comment by eltonjhony** [comment]
I'm facing the same issue.

**Comment by oldalton** [comment]
Hi, can you make sure you followed keychain setup steps as described here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal? Thanks.

**Comment by oldalton** [comment]
Did the issue get resolved? Thanks.
