### ISSUE TITLE
Can MSALWebviewParameters be used with SwiftUI to fetch a token interactively?

### ISSUE THREAD

**Issue by jyotimathur** [Azure-Samples/ms-identity-mobile-apple-swift-objc#68]
I have an app that used SwiftUI instead of UIKit. I want to use MSAL library to acquire a token interactively. I see that MSALWebviewParameters support display using UIViewController. Is there a way to use swift ui based views here?

**Comment by antrix1989** [comment]
Closing as a [duplicate](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/953).
