### ISSUE TITLE
accessToken not generated after adding Scope

### ISSUE THREAD

**Issue by bhandaribhumin** [Azure-Samples/ms-identity-mobile-apple-swift-objc#69]
let kScopes: [String] = ["user.read","Calendars.Read","Calendars.ReadWrite"] 

App Permission:
<img width="364" alt="Screenshot 2020-08-21 at 5 17 15 PM" src="https://user-images.githubusercontent.com/3336047/90890298-531b6700-e3d7-11ea-9439-d9a2492e06dd.png">

**Error Log:** 

```
Could not acquire token silently: Error Domain=MSALErrorDomain Code=-50003 "(null)" UserInfo={MSALDeclinedScopesKey=(
  "Calendars.Read",
  "Calendars.ReadWrite"
), MSALGrantedScopesKey=(
    "User.Read",
    email
), MSALErrorDescriptionKey=Server returned less scopes than requested

TID=101906 MSAL 1.1.3 iOS 14.0 [2020-08-21 12:21:19 - ] Server returned less scopes than requested, granted scopes: {(
    "User.Read",
    profile,
    openid,
    email
)}
TID=101906 MSAL 1.1.3 iOS 14.0 [2020-08-21 12:21:19 - ] Removing reserved scopes from granted scopes: {(
    openid,
    profile,
    "offline_access"
)}
TID=101906 MSAL 1.1.3 iOS 14.0 [2020-08-21 12:21:19 -] Final granted scopes: {(
    "User.Read",
    profile,
    openid,
    email
)}
TID=101906 MSAL 1.1.3 iOS 14.0 [2020-08-21 12:21:19 -] [MSAL] Silent flow finished. Result (null), error: -51415 error domain: MSIDOAuthErrorDomain
TID=101906 MSAL 1.1.3 iOS 14.0 [2020-08-21 12:21:19 - ] [MSAL] acquireTokenSilent returning with error: (MSALErrorDomain, -50003) Masked(not-null)
```

**Comment by kaisong1990** [comment]
@bhandaribhumin Thanks for providing the information. Based on the info from the error log, there is no ```Calendars.Read``` and ```Calendars.ReadWrite``` in the final granted scopes.

Could you try to reproduce the issue and provide correlation id for further investigation?

**Comment by bhandaribhumin** [comment]
Yes I was using the same client ID I confirmed.

**Comment by bhandaribhumin** [comment]
@kaisong1990 awaiting please help me on this.

**Comment by bhandaribhumin** [comment]
@kaisong1990 is below policy is blocking me for call Graph API.
<img width="341" alt="thumbnail_image001" src="https://user-images.githubusercontent.com/3336047/91726847-853e7d00-ebbe-11ea-8bea-5e366e0e5872.png">

**Comment by jasoncoolmax** [comment]
Did your issue go away once you uncheck the above box?

**Comment by bhandaribhumin** [comment]
This is recommended from Microsoft for our organization.

**Comment by aherciya** [comment]
@bhandaribhumin Are you still seeing this issue?

**Comment by bhandaribhumin** [comment]
@aherciya thanks for asking but our org. admin is still looking for remove this policy from azure. Awaiting acknowledge from admin :)

**Comment by mipetriu** [comment]
Closing this issue due to lack of response. Feel free to reopen when the policy can be removed.
