### ISSUE TITLE
integration with auth broker (i.e. Microsoft Authenticator)

### ISSUE THREAD

**Issue by nicolgit** [Azure-Samples/ms-identity-mobile-apple-swift-objc#70]
I was looking for a sample that shows SSO and authentication broker support of MSAL on iOS, it is in roadmap or available? something similar to the this for Android https://github.com/Azure-Samples/ms-identity-android-java

**Comment by NerevarineRule** [comment]
@oldalton  Would you by any chance have a diagram / related document?

**Comment by NerevarineRule** [comment]
Hi, thank you for your inquiry. Could you please refer to this link for the information that you are looking for? 
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios
