### ISSUE TITLE
presentationStyle  in MSALWebviewParameters does not work

### ISSUE THREAD

**Issue by iadcialim** [Azure-Samples/ms-identity-mobile-apple-swift-objc#74]
func initWebViewParams() 
{
    self.webViewParamaters = MSALWebviewParameters(authPresentationViewController: self)
    webViewParamaters?.presentationStyle = .fullScreen   <<< does not work
}

It will always show using .automatic. 
Tested in iOS14

**Comment by ameyapat** [comment]
@iadcialim For iOS 14 ASWebAuthenticationSession is used by default and it will ignore any presentationStyle we set.
As per doc,  
Note that presentationStyle has no effect when webviewType == MSALWebviewType.MSALWebviewTypeDefault or
 webviewType == MSALWebviewType.MSALWebviewTypeAuthenticationSession.

You may chose to not use ASWebAuthenticationSession by setting webViewType in webViewParameters. The implications of doing so are highlighted here : https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews

**Comment by ameyapat** [comment]
Closing issue. Please reopen if there are still issues. Thanks!
