### ISSUE TITLE
Can MSAL iOS macOS be used to implement client credentials flow?

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [Azure-Samples/ms-identity-mobile-apple-swift-objc#75]
Can this library be used to implement [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) for the azure active directory? If so please provide me with the samples or documentation on doing so

**Comment by kaisong1990** [comment]
We closed this issue as it is a duplication of this one

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1186
