### ISSUE TITLE
WKWebview Silent Login - Session not working

### ISSUE THREAD

**Issue by kepe94** [Azure-Samples/ms-identity-mobile-apple-swift-objc#81]
The silent login doesn’t work on the WKWebview, by logging in with the method ‘acquireTokenSilent’ using the wkWebView as webviewType.

After logging in, it requires to login again when opening the url with WKWebview.

How could I solve this issue?

Thank you in advance

**Comment by jasoncoolmax** [comment]
Hi @kepe94 , I will close this one as it is a duplicate as https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1481.

Thank you!
