### ISSUE TITLE
Hi, Trying to make Msauth for B2C 

### ISSUE THREAD

**Issue by ubrainrepo** [Azure-Samples/ms-identity-mobile-apple-swift-objc#82]
step 1:) I have done setup server side with iOS bundle ID and get the Auth 
Step 2:)  i have done also URL schema setup on the application 

1) URL scema code 

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.XXXXXXX</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.com.XXXXXXX</string>
			</array>
		</dict>
	</array>

```
Code for application 

        do {
            // Create an instance of MSALPublicClientApplication with proper config
            let authority = try MSALB2CAuthority(url: URL(string: "https://<MyApp>.b2clogin.com/tfp/segensnap.onmicrosoft.com/B2C_1_signupsignin")!)
            let pcaConfig = MSALPublicClientApplicationConfig(clientId: "<SCLIENT ID>", redirectUri: nil, authority: authority)
            pcaConfig.knownAuthorities = [authority]
            
            let application = try MSALPublicClientApplication(configuration: pcaConfig)
                    
            let viewController = self /*replace with your main presentation controller here */
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: ["https://<MyApp>.onmicrosoft.com/86898dd6-ffee-4cbc-a553-28885aa169c2/access_as_user"], webviewParameters: webViewParameters)
                    
            application.acquireToken(with: interactiveParameters) { (result, error) in
                        
                guard let result = result else {
                    print("ERROR COME PLEASE CHECK::")
                    print(error!) /* MSAL token acquisition failed, check error information */
                    return
                        }
                        
                        let accessToken = result.accessToken
                        let account = result.account
                print("TOKE DETAILS::")
                print(accessToken)
                print(account)
                        
            }
        }
        catch {
            print("THIS IS ERROR ON CATCH")
            print(error) 
        }

Getting error "Safari cannot open the page because the address is invalid"

![2022_06_25T08_33_06_765Z](https://user-images.githubusercontent.com/68951795/175765459-7e4140e9-780d-418a-9866-511b3f2bf212.jpeg)

**Comment by kaisong1990** [comment]
@ubrainrepo Thanks for your question, looks like the Authority url is not valid, and I would suggest checking this link:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin#what-endpoints-does-this-apply-to

**Comment by jasoncoolmax** [comment]
Feel free to reopen the ticket if issue remains.
