### ISSUE TITLE
MSAL says broker is not enabled for device

### ISSUE THREAD

**Issue by geohei** [Azure-Samples/ms-identity-mobile-apple-swift-objc#83]
I'm using sample package below to make myself familiar with MSAL 1.2.2 (MSALiOS).
https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc
Microsoft Authenticator is installed on the device and correctly used by sample code above.
All works fine.

But ... if I implement the code in my app, I get an error while getting device information:

```
msalApplicationContext?.getDeviceInformation(with: nil, completionBlock: { (deviceInformation, error) in
    guard let deviceInfo = deviceInformation else { return }
    msalCurrentDeviceMode = deviceInfo.deviceMode
}
```

`Optional(Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Broker is not enabled for this operation. Please make sure you have enabled broker support for your application, MSALInternalErrorCodeKey=-42714})`

The prerequisites are set:
1. Keychain Sharing
`com.microsoft.adalcache`
2. Info.plist
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>msauthv2</string>
    <string>msauthv3</string>
</array>
```
3. AppDelegate callback function is implemented.

`MSALError.h` says:
```
/*
Broker is either not found on device or not available for this configuration.
*/
MSALInternalBrokerNotAvailable                      = -42714

```
Am I missing something or did the docs miss to mention something?
In other words ... when does `getDeviceInformation()` return an error?

**Comment by mipetriu** [comment]
@geohei It looks like the same question is posted [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1523). Discussion is happening there, so I will close this as a duplicate.
