### ISSUE TITLE
[In app browser issue] Microsoft login not redirecting back to app after MFA validation

### ISSUE THREAD

**Issue by argelj289** [Azure-Samples/ms-identity-mobile-apple-swift-objc#84]
Hi,

Our users encountering an issue with the Micosoft Online login after MFA validation with our Mobile app

As we observed, the Microsoft Online login is not redirecting back to the Mobile app and it's stuck there and just loading

We noticed also that this happens when there is another app that uses Microsoft Online login as login authentication

Kindly check and hope that this will be fixed as soon as possible.

**Comment by mipetriu** [comment]
Hi @argelj289, I will double-check if I can repro the issue.

I'm not sure I understand what you're referring to when you mention the "Microsoft Online login"? Could you tell me a little bit more about your scenario?

**Comment by jasoncoolmax** [comment]
Close it for now. Feel free to reopen if more info can be provided.

**Comment by argelj289** [comment]
> Hi @argelj289, I will double-check if I can repro the issue.
> 
> I'm not sure I understand what you're referring to when you mention the "Microsoft Online login"? Could you tell me a little bit more about your scenario?

Hi @mipetriu - 
the scenario is that there are 2 or more apps installed to the user's mobile device that uses the same login authentication as our app

when the user tries to login to our app using Microsoft Authenticator or any authentication available in MFA, it always stuck in the login page and does not go back to the app they opened
