### ISSUE TITLE
Configure multiple MSAL dynamically for B2B app 

### ISSUE THREAD

**Issue by dsngeu** [Azure-Samples/ms-identity-mobile-apple-swift-objc#86]
Hi, I'm working on production B2B where other business uses our application but at this time problem is that when a new business wants to use our application then I have added their client I'd in info.plist to support the new SSO and have to upload app to apple store every time. 

Is there any way to set up the masl or configure new client Id info.plist dynamically. New setup industry details should be fetched from the server and without releasing a new version of the app it should work for all client I'd. 

Currently, i have to setup the client Id in plist as
Below 👇

**<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>msauth.[BUNDLE_ID]</string>
        </array>
    </dict>
</array>
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>msauthv2</string>
    <string>msauthv3</string>
</array>**

What is your view on this? Is it doable without adding a new client id every time and making a new release? 
can we do this at runtime? 

@chanezon 
@erikstmartin 
@kalyankrishna1 
@asw101

**Comment by jasoncoolmax** [comment]
Currently we don't support it. The reason is that we have certain restrictions on redirect uri that is being used. The redirect uri needs to be consistent with the app bundle id, such that an app cannot pretend to be some other app, which is a security concern.
