### ISSUE TITLE
MSALErrorDomain error-5000

### ISSUE THREAD

**Issue by xiaochuan4938** [Azure-Samples/ms-identity-mobile-apple-swift-objc#87]
Some times user with Outlook  or Skype installed in their devices get  into this error "The operation couldn't  be completed (MSALErrorDomain error -5000)". 
<img width="708" alt="image" src="https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc/assets/15375679/264b461d-7511-4408-b0d7-ac14a9c784a9">

**Comment by jasoncoolmax** [comment]
Hi @xiaochuan4938, -50000 is MSALErrorInternal. Could you please provide the MSAL logs such that I can help investigate? Thank you!

**Comment by xiaochuan4938** [comment]
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALInternalErrorCodeKey=-42402, MSALCorrelationIDKey=EF0E0F78-758C-4293-8A1E-37CDA1C0C579}  @jasoncoolmax

**Comment by jasoncoolmax** [comment]
Yes, the error code means that the previous interactive call is not finished yet. You should either wait for user to finish the interaction, or cancel it programmatically.

**Comment by xiaochuan4938** [comment]
<img width="986" alt="image" src="https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc/assets/15375679/8a4f1059-e7c3-4151-80dd-ca98138758b9">

The issues is still there, what should I do next?
